version: '3.9'

volumes:
  worker_data:

services:
  bot-server:
    container_name: bot-server
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
#    command: "python server.py"
    env_file:
      - ./.env.dev
    volumes:
      - .:/data